version: '3.9'

services:
  web:
    build: .
    restart: always
    command: python /app/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
      - ./learning/templates/common/timestamps_form.html:/app/learning/templates/common/timestamps_form.html
      - ./.venv/Lib/site-packages/pytube/captions.py:/usr/local/lib/python3.10/site-packages/pytube/captions.py
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
  celery:
    restart: always
    build:
      context: .
    command: celery -A django_project worker -l info
    volumes:
      - .:/app
      - ./learning/templates/common/timestamps_form.html:/app/learning/templates/common/timestamps_form.html
      - ./.venv/Lib/site-packages/pytube/captions.py:/usr/local/lib/python3.10/site-packages/pytube/captions.py
    # env_file:
    #   - ./.venv
    depends_on:
      - web
      - rabbitmq3
  rabbitmq3:
    container_name: "rabbitmq"
    image: rabbitmq:3-management-alpine
    ports:
      - 5672:5672
      - 15672:15672

volumes:
  postgres_data:
