version: '3.7'

services:
  web:
    container_name: web
    build: .
    restart: always
    command: ["/wait-for-it.sh", "db:5432", "--", "gunicorn", "--bind", "0.0.0.0:8000", "--workers", "3", "django_project.wsgi:application"]
    volumes:
      - .:/app
      - static_files:/app/staticfiles
      - ./learning/templates/common/timestamps_form.html:/app/learning/templates/common/timestamps_form.html
      - ./.venv/Lib/site-packages/pytube/captions.py:/usr/local/lib/python3.10/site-packages/pytube/captions.py
    expose:
      - 8000
    env_file: .env
    depends_on:
      - db
  nginx:
    container_name: nginx
    restart: always
    image: nginx:stable-perl
    volumes:
      - static_files:/app/staticfiles
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    ports:
      - 80:80
      - 443:443
    depends_on:
      - web
      - db
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
  certbot:
    container_name: certbot
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
  db:
    container_name: db
    image: postgres:13
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file: .env
  celery:
    container_name: celery
    restart: always
    build:
      context: .
    command: celery -A django_project worker -l info -B # -B for worker, but prolly not good for production
    # command: celery -A django_project worker -l info # Original, but crontab doesn't work
    # command: celery -A django_project beat -l info # beat instead of worker for crontab
    volumes:
      - .:/app
      - ./learning/templates/common/timestamps_form.html:/app/learning/templates/common/timestamps_form.html
      - ./.venv/Lib/site-packages/pytube/captions.py:/usr/local/lib/python3.10/site-packages/pytube/captions.py
    env_file:
      - .env
    depends_on:
      - web
      - rabbitmq3
  rabbitmq3:
    container_name: rabbitmq
    image: rabbitmq:3-management-alpine
    ports:
      - 5672:5672
      - 15672:15672

volumes:
  postgres_data:
  nginx_secrets:
  static_files: