# Generated by Django 4.1.1 on 2023-02-12 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='language',
            field=models.CharField(blank=True, choices=[('de', 'German'), ('en', 'English'), ('zh-HK', 'Chinese'), ('pt-PT', 'Portuguese'), ('fr-FR', 'French'), ('ja', 'Japanese'), ('ru', 'Russian'), ('it', 'Italian')], max_length=40, null=True),
        ),
    ]
